site_name: "Algo Curriculum"
repo_url: https://github.com/Crisforlove/Algo.git
theme:
  name: 'material'

nav:
  - Home: index.md
  - Java:
      - Lesson 1: lesson1/Lesson1 Java.md
      - Lesson 2: lesson2/Lesson2 Java.md
      - Lesson 3: lesson3/Lesson3 Java.md
      - Lesson 4: lesson4/Lesson4 Java.md
      - Lesson 5: lesson5/Lesson5 Java.md
      - Lesson 6: lesson6/Lesson6 Java.md
      - Lesson 7: lesson7/Lesson7 Java.md
      - Lesson 8: lesson8/Lesson8 Java.md
      - Lesson 9: lesson9/Lesson9 Java.md
      - Lesson 10: lesson10/Lesson10 Java.md
      - Lesson 11: lesson11/Lesson11 Java.md
      - Lesson 12: lesson12/Lesson12 Java.md
      - Lesson 13: lesson13/Lesson13 Java.md
      - Lesson 14: lesson14/Lesson14 Java.md
      - Lesson 15: lesson15/Lesson15 Java.md
  - Python:
      - Lesson 1: lesson1/Lesson1 Python.md
      - Lesson 2: lesson2/Lesson2 Python.md
      - Lesson 3: lesson3/Lesson3 Python.md
      - Lesson 4: lesson4/Lesson4 Python.md
      - Lesson 5: lesson5/Lesson5 Python.md
      - Lesson 6: lesson6/Lesson6 Python.md
      - Lesson 7: lesson7/Lesson7 Python.md
      - Lesson 8: lesson8/Lesson8 Python.md
      - Lesson 9: lesson9/Lesson9 Python.md
      - Lesson 10: lesson10/Lesson10 Python.md
      - Lesson 11: lesson11/Lesson11 Python.md
      - Lesson 12: lesson12/Lesson12 Python.md
      - Lesson 13: lesson13/Lesson13 Python.md
      - Lesson 14: lesson14/Lesson14 Python.md
      - Lesson 15: lesson15/Lesson15 Python.md
  - C++:
      - Lesson 1: lesson1/Lesson1 C++.md
      - Lesson 2: lesson2/Lesson2 C++.md
      - Lesson 3: lesson3/Lesson3 C++.md
      - Lesson 4: lesson4/Lesson4 C++.md
      - Lesson 5: lesson5/Lesson5 C++.md
      - Lesson 6: lesson6/Lesson6 C++.md
      - Lesson 7: lesson7/Lesson7 C++.md
      - Lesson 8: lesson8/Lesson8 C++.md
      - Lesson 9: lesson9/Lesson9 C++.md
      - Lesson 10: lesson10/Lesson10 C++.md
      - Lesson 11: lesson11/Lesson11 C++.md
      - Lesson 12: lesson12/Lesson12 C++.md
      - Lesson 13: lesson13/Lesson13 C++.md
      - Lesson 14: lesson14/Lesson14 C++.md
      - Lesson 15: lesson15/Lesson15 C++.md
